CREATE TABLE IF NOT EXISTS `gb_discounts`(
	`DiscountID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`caption` VARCHAR(64) NOT NULL DEFAULT "",
	`from` INT UNSIGNED NOT NULL DEFAULT 1,
	`to` INT UNSIGNED NOT NULL DEFAULT 1,
	`essence` VARCHAR(1024) NOT NULL DEFAULT "",
	`sticker` VARCHAR(8) NOT NULL DEFAULT "",
	`discount` TINYINT(3) UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY(`DiscountID`)
)ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS `gb_filters`(
	`id` INT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
	`value` VARCHAR(48) NOT NULL,
	`translit` VARCHAR(48) NOT NULL,
	PRIMARY KEY(`id`),
	UNIQUE(`translit`)
)ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS `gb_items`(
	`PageID` INT UNSIGNED NOT NULL,
	`ItemID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`DiscountID` INT UNSIGNED,
	`tid` INT UNSIGNED DEFAULT 2,
	`label` VARCHAR(24) NOT NULL DEFAULT '',
	`preview` VARCHAR(256) NOT NULL DEFAULT '/images/NIA.jpg',
	`images` VARCHAR(768) NOT NULL DEFAULT '[]',
	`purchase` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
	`selling` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
	`currency` ENUM('USD','EUR','UAH') NOT NULL DEFAULT 'USD',
	`units`  ENUM('шт.','м','м²','г.','кг.','л.') NOT NULL DEFAULT 'шт.',
	`dumping` TINYINT(3) UNSIGNED NOT NULL DEFAULT 0,
	`outstock` ENUM('not available','under the order') NOT NULL DEFAULT 'not available',
	PRIMARY KEY(`ItemID`),
	FOREIGN KEY (`PageID`) REFERENCES `gb_pages`(`PageID`)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY (`DiscountID`) REFERENCES `gb_discounts`(`DiscountID`)
		ON UPDATE CASCADE
		ON DELETE SET NULL,
	FOREIGN KEY (`tid`) REFERENCES `gb_tagination`(`tid`)
		ON UPDATE CASCADE
		ON DELETE SET NULL
)ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS `gb_models`(
	`PageID` INT UNSIGNED NOT NULL,
	`ItemID` INT UNSIGNED,
	`CategoryID` INT UNSIGNED NOT NULL,
	`RelatedCategoryID` INT UNSIGNED NOT NULL,
	`tid` INT UNSIGNED DEFAULT 2,
	`name` VARCHAR(256) NOT NULL DEFAULT '',
	`brand` VARCHAR(32) NOT NULL DEFAULT '',
	`subtemplate` VARCHAR(32) NOT NULL DEFAULT '',
	`status` ENUM('available','not available') NOT NULL DEFAULT 'not available',
	`options` VARCHAR(2048) NOT NULL DEFAULT '{}',
	`description` BLOB,
	PRIMARY KEY(`PageID`),
	FOREIGN KEY (`PageID`) REFERENCES `gb_pages`(`PageID`)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY (`ItemID`) REFERENCES `gb_items`(`ItemID`)
		ON UPDATE CASCADE
		ON DELETE SET NULL,
	FOREIGN KEY (`CategoryID`) REFERENCES `gb_sitemap`(`PageID`)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY (`RelatedCategoryID`) REFERENCES `gb_sitemap`(`PageID`)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY (`tid`) REFERENCES `gb_tagination`(`tid`)
		ON UPDATE CASCADE
		ON DELETE SET NULL
)ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS `gb_stock`(
	`ItemID` INT UNSIGNED NOT NULL,
	`stock` VARCHAR(24) NOT NULL DEFAULT 'main',
	`remainder` INT(4) UNSIGNED NOT NULL DEFAULT 0,
	FOREIGN KEY (`ItemID`) REFERENCES `gb_items`(`ItemID`)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	INDEX(`stock`),
	UNIQUE(`stock`, `ItemID`)
)ENGINE=InnoDB CHARACTER SET utf8;